name: Test, Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Docker variables
        run: |
          echo "Docker username: ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "Image tag: ${{ secrets.DOCKERHUB_USERNAME }}/node-docker-demon:latest"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Verify Docker login
        run: docker info

      - name: Build Docker image only
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/node-docker-demon:latest .

      - name: Push Docker image manually
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-docker-demon:latest